src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 70)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $urlImage = null;

    #[ORM\ManyToMany(targetEntity: Ingredient::class, inversedBy: 'produits')]
    private Collection $ingredients;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeProduit $typeProduit = null;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: DetailCommande::class, orphanRemoval: true)]
    private Collection $detailCommandes;

    #[ORM\Column]
    private ?bool $Disponible = null;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->detailCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->urlImage;
    }

    public function setUrlImage(string $urlImage): static
    {
        $this->urlImage = $urlImage;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): static
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): static
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }

    public function getTypeProduit(): ?TypeProduit
    {
        return $this->typeProduit;
    }

    public function setTypeProduit(?TypeProduit $typeProduit): static
    {
        $this->typeProduit = $typeProduit;

        return $this;
    }

    /**
     * @return Collection<int, DetailCommande>
     */
    public function getDetailCommandes(): Collection
    {
        return $this->detailCommandes;
    }

    public function addDetailCommande(DetailCommande $detailCommande): static
    {
        if (!$this->detailCommandes->contains($detailCommande)) {
            $this->detailCommandes->add($detailCommande);
            $detailCommande->setProduit($this);
        }

        return $this;
    }

    public function removeDetailCommande(DetailCommande $detailCommande): static
    {
        if ($this->detailCommandes->removeElement($detailCommande)) {
            // set the owning side to null (unless already changed)
            if ($detailCommande->getProduit() === $this) {
                $detailCommande->setProduit(null);
            }
        }

        return $this;
    }

    public function isDisponible(): ?bool
    {
        return $this->Disponible;
    }

    public function setDisponible(bool $Disponible): static
    {
        $this->Disponible = $Disponible;

        return $this;
    }

}

src/Controller/PanierController.php
<?php

namespace App\Controller;


use App\Repository\CollaborateurRepository;
use App\Repository\CommandeRepository;
use App\Repository\DetailCommandeRepository;
use App\Repository\EtatRepository;
use App\Repository\ProduitRepository;
use App\Repository\TailleProduitRepository;
use App\Repository\UserMessageRepository;
use DateInterval;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PanierController extends AbstractController
{
    #[Route('/panier', name: '_panier')]
    public function index(TailleProduitRepository $tailleProduitRepository, UserMessageRepository $userMessageRepository, CommandeRepository $commandeRepository, ProduitRepository $produitRepository, EtatRepository $etatRepository): Response
    {
        $messagesNonLu = $userMessageRepository->findBy(['checked' => 0]);
        $utilisateur = $this->getUser();
        $etatCreer = $etatRepository->findOneBy(['id' => 1]);
        $pizzas = $produitRepository->findAll();

//////////////////////////////// TOOLTIP ///////////////////////////////////////////////////////////////////////////////////////////
        $result = $this->tooltip($commandeRepository, $tailleProduitRepository, $produitRepository);
        if($result){
            $detailsCommandePanier = $result['detailsCommandePanier'];
            $prixDuPanier = $result['prixDuPanier'];
        } else {
            $detailsCommandePanier = [];
            $prixDuPanier = 0;
        }
//////////////////////////////////////////////////////////////////////////////

        return $this->render('panier/index.html.twig', compact('detailsCommandePanier', 'prixDuPanier', 'pizzas', 'messagesNonLu'));
    }

    #[Route('/payementPanier', name: '_payementPanier')]
    public function payementPanier(ProduitRepository $produitRepository, CommandeRepository $commandeRepository, EtatRepository $etatRepository, EntityManagerInterface $entityManager): Response
    {
        $etatCreer = $etatRepository->findOneBy(array('id' => 1));
        $etatPayer = $etatRepository->findOneBy(array('id' => 2));
        $now = new DateTime();
        $utilisateur = $this->getUser();
        $heurePreparation = $now->add(new DateInterval('PT30M'));
        $heureLivraison = $heurePreparation->add(new DateInterval('PT30M'));
        $derniereCommande = $commandeRepository->findOneBy(
            ['collaborateur' => $utilisateur, 'etat' => '1'],
            ['id' => 'DESC']
        );

        if (($derniereCommande->getEtat()->getId()) === $etatCreer->getId()) {
            $derniereCommande->setEtat($etatPayer);
            $derniereCommande->setDateHeurePreparation($heurePreparation);
            $derniereCommande->setDateHeureLivraison($heureLivraison);
            $entityManager->persist($derniereCommande);
            $entityManager->flush();
            return $this->redirectToRoute('_accueil');
        }
        return $this->render('panier/index.html.twig');
    }

    #[Route('/suppressionDuPanier/{id}', name: '_suppressionDuPanier')]
    public function suppressionDuPanier($id, DetailCommandeRepository $detailCommandeRepository, EntityManagerInterface $entityManager, CollaborateurRepository $collaborateurRepository): Response
    {
        $articleASupprimer = $detailCommandeRepository->findOneBy(array('id' => $id));
        $commande = $articleASupprimer->getCommande();
        $idCommande = $commande->getId();
        if ($articleASupprimer) {
            $entityManager->remove($articleASupprimer);
            $entityManager->flush();
            $detailCommandeRestant = $detailCommandeRepository->findBy(['commande' => $idCommande]);
            if (empty($detailCommandeRestant)) {
                $utilisateur = $this->getUser();
                $user = $collaborateurRepository->findOneBy(array('id' => $utilisateur->getId()));
                $user->setPanier(0);
                $entityManager->persist($user);
                $entityManager->flush();
            }
            return $this->redirectToRoute('_accueil');
        }
        return $this->render('panier/detail.html.twig');
    }

    #[Route('/etatPrepare{id}/{idLivreur}', name: '_etatPrepare')]
    public function etatPrepare($id, $idLivreur, CommandeRepository $commandeRepository, CollaborateurRepository $collaborateurRepository, EtatRepository $etatRepository, EntityManagerInterface $entityManager): Response
    {
        $commande = $commandeRepository->findOneBy(array('id' => $id));
        $livreur = $collaborateurRepository->findOneBy(array('id' => $idLivreur));
        $etatPreparee = $etatRepository->findOneBy(array('id' => 3));
        if ($commande) {
            $commande->setEtat($etatPreparee);
            $commande->setLivreur($livreur);
            $entityManager->flush();
            return $this->redirectToRoute('_preparationCommande');
        }
        return $this->render('commande/preparationCommande.html.twig');
    }

    public function prixDuPanier($derniereCommande, $tailleProduitRepository, $produitRepository, $detailsCommandePanier)
    {
        $prixDuPanier = 0; // Instancie une variable de prix de panier à 0 qui sera envoyé au twig
        $tailleLarge = $tailleProduitRepository->findOneBy(array('id' => 2)); // récupère la taille large pour une condition (prix)
        if ($derniereCommande != null) { // Si il y a une dernière commande
            $etatDerniereCommande = $derniereCommande->getEtat();
            if ($etatDerniereCommande->getId() == 1) { // Si elle est a l'état créé
                foreach ($detailsCommandePanier as $detail) {
                    $idProduit = $detail->getProduit()->getId();
                    $pizza = $produitRepository->findOneBy(array('id' => $idProduit));
                    if ($detail->getTaille() === $tailleLarge) { // Si il y a une taille large on change le prix
                        $prixDuDetail = (($pizza->getPrix() + 5) * $detail->getQuantite());
                    } else {
                        $prixDuDetail = ($pizza->getPrix() * $detail->getQuantite());
                    }

                    $prixDuPanier = ($prixDuPanier + $prixDuDetail); // Total du panier
                }
            }
        }
        return $prixDuPanier;
    }

    public function tooltip($commandeRepository, $tailleProduitRepository, $produitRepository)
    {
        $result = [];
        $utilisateur = $this->getUser();
        $derniereCommande = $commandeRepository->findOneBy(
            ['collaborateur' => $utilisateur, 'etat' => '1'],
            ['id' => 'DESC']
        );
        if ($derniereCommande) {
            $detailsCommandePanier = $derniereCommande->getDetailsCommandeTrieesParNomProduit();
            $prixDuPanier = $this->prixDuPanier($derniereCommande, $tailleProduitRepository, $produitRepository, $detailsCommandePanier);

            $result = [
                'detailsCommandePanier' => $detailsCommandePanier,
                'prixDuPanier' => $prixDuPanier,
            ];
        }
        return $result;
    }
}

templates/panier/detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}PizzaOnLine - Détail{% endblock %}

{% block body %}

<h2 class="flex item-center justify-center text-5xl mt-2 underline underline-offset-8 text-gray-50"> {{ pizza.nom }} </h2>

<div class="w-full flex items-center justify-center mt-10">
    <div class="hidden" id="typeProduit">{{ pizza.typeProduit.libelle }}</div>
    <div class="w-3/4 flex flex-wrap justify-center mb-4">
        <div class="w-1/2 flex justify-end ">
            <img src="./../images/{{ pizza.urlImage }}" style="width: 400px; height: 300px;"
                 class="border-[1px] border-gray-400 mr-6">
        </div>
        <div class="w-1/2">
            <div class="text-2xl mb-6 mt-4">
                {{ pizza.description }}
            </div>
            {% if pizza.typeProduit.libelle == 'Pizza' %}
            <div class="text-2xl mb-6 flex items-center">
                {% else %}
                <div class="text-2xl mb-6 flex items-center hidden">
                    {% endif %}
                    <span class="font-bold text-gray-50">Ingrédients :</span>
                    {% set viandePresente = false %}
                    {% for viande in viandes %}
                        {% for ingredient in pizza.Ingredients %}
                            {% if viande == ingredient.nom %}
                                {% set viandePresente = true %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}

                    {% if viandePresente %}
                        <img src="{{ asset('images/bifteck.png') }}" style="width: 35px; height: 35px;" class="ml-4">
                    {% else %}
                        <img src="{{ asset('images/legume.png') }}" style="width: 35px; height: 35px;" class="ml-4">
                    {% endif %}
                </div>
                {% if pizza.typeProduit.libelle == 'Pizza' %}
                <div class="text-2xl ">
                    {% else %}
                    <div class="text-2xl hidden">
                        {% endif %}
                        {% for ingredient in pizza.Ingredients %}
                            {{ ingredient.nom }}{{ not loop.last ? ', ' }}
                        {% endfor %}
                    </div>
                    <div class="flex flex-col text-2xl mt-5">

                        <div class="font-bold mb-2 text-gray-50">Prix :</div>
                        <div class="flex flex-wrap">
                            <div class="">médium : {{ (pizza.prix) | number_format(2, '.', ',') }} €</div>
                            <div class="ml-8 flex justify-end">large
                                : {{ (pizza.prix + 5) | number_format(2, '.', ',') }} €
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if app.user and pizza.disponible == true %}
        <div class="w-full flex justify-center items-center mt-2">
            <div class="w-1/3 text-2xl font-semibold flex justify-center items-center underline underline-offset-4 text-gray-50">
                Pour
                ajouter la pizza à votre panier
                :
            </div>
        </div>
        <div class="w-full flex justify-center items-center mt-4">
            <div class="w-1/3 justify-center items-center border-2 border-white px-2 py-4 rounded">
                {{ form_start(detailCommandeForm) }}

                <div class="text-2xl text-black font-bold hidden">
                    {{ form_widget(detailCommandeForm.quantite, {'id': 'quantiteModal','attr': {'style': 'width : 200px;  text-align: center; font-size: 1.25rem;'}}) }}
                </div>
                <div class="mb-7 flex justify-center items-center">
                    <div class="mr-5 text-2xl mb-2 text-gray-50">
                        {{ form_label(detailCommandeForm.quantite) }} :
                    </div>
                    <div class="text-2xl text-black font-bold flex flex-crap">
                        <button type="button"
                                data-input-counter-decrement="quantity-input" id="decrement"
                                class="  bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-s-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
                            <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 2">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2" d="M1 1h16"/>
                            </svg>
                        </button>
                        <input type="text" data-input-counter data-input-counter-min="1"
                               data-input-counter-max="50" aria-describedby="helper-text-explanation" style="width:65px"
                               class="bg-gray-50 border-x-0 border-gray-300 h-11 text-center text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full py-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                               placeholder="999" value="0" id="inputQuantite"
                               required>
                        <button type="button" id="increment"
                                data-input-counter-increment="quantity-input"
                                class=" bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
                            <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2" d="M9 1v16M1 9h16"/>
                            </svg>
                        </button>
                    </div>
                </div>
                <div class="mb-4 text-2xl flex justify-center items-center">
                    <div class="mr-4 text-gray-50">
                        Taille :
                    </div>
                    <div class=" custom-checkbox-container flex flex-wrap">
                        {% for taille in detailCommandeForm.taille %}
                            <div class="text-gray-50">
                                {{ form_widget(taille, {'attr': {'class': 'custom-checkbox '}}) }}
                                {{ form_label(taille) }}
                            </div>
                        {% endfor %}
                    </div>

                </div>
                <div class="text-3xl hover:text-red-500 duration-200 font-bold mt-6 flex justify-center items-center">
                    <div>
                        {{ form_widget(detailCommandeForm.ajouter, {'attr': {'class': 'btn flex text-2xl justify-center items-center text-white bg-blue-600 hover:bg-blue-700 font-bold border-transparent'}}) }}
                    </div>
                </div>
                {{ form_end (detailCommandeForm) }}
            </div>
        </div>
    {% else %}
        <div class="w-full flex justify-center items-center mt-2">
            <div class="w-1/2 flex  text-3xl font-semibold justify-center items-center text-red-600 ">
                <img src="{{ asset('images/rupture-de-stock.png') }}" alt="Rupture de stock"
                     style="width: 150px; height: 125px;">
                <div class="ml-5">Pizza actuellement non disponible à la vente</div>
            </div>
            {% endif %}
            {% if not app.user %}
                <div class="flex justify-center item-center text-3xl hover:text-red-500 duration-200 font-bold mt-10">
                    <div>
                        <a href="{{ path('app_login') }}">Connectez-vous pour commander</a>
                    </div>
                </div>
            {% endif %}
        </div>
        <script src="{{ asset('build/app.js') }}"></script>
        <script>
            window.onload = function () {
                initTest();
            };
        </script>
        {% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PizzaOnLine - Panier{% endblock %}

{% block body %}


    <h2 class="flex item-center justify-center text-5xl mt-2 text-gray-50"> Votre panier </h2>

    {% if detailsCommandePanier is not empty %}
        <div class="w-full justify-center items-center flex mt-8 ">
            <div class="w-1/2 border-white border-2 py-3 mb-20">
                {% for detailCommande in detailsCommandePanier %}
                    <div class="mx-4 px-1 py-1 rounded flex items-center justify-center mb-3 bg-gray-300 mt-2 border-4 border-amber-800	">
                        <div class="mt-1 text-xl w-1/3 " id="photo">
                            <div class="flex justify-center">
                                {% for pizza in pizzas %}
                                    {% if pizza.nom == detailCommande.produit.nom %}
                                        <img src="images/{{ pizza.urlImage }}"
                                             style="width: 175px; height: 125px;"
                                             class="mb-2 rounded border border-black">
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class=" text-3xl mt-2 w-2/3 p-1" id="contenu">
                            <div class="flex items-center text-black mb-3 policePizza">
                                {{ detailCommande.produit.nom }}
                            </div>
                            <div class="flex text-black justify-between policePizza">
                                <div class="text-2xl">Quantité : {{ detailCommande.quantite }}</div>
                                <div class="text-2xl ml-4">Taille : {{ detailCommande.taille.libelle }}</div>
                                <div class="text-2xl ml-4">Prix :
                                    {% if detailCommande.taille.id == 2 %}
                                        {{ ((5+detailCommande.produit.prix) * detailCommande.quantite) | number_format(2, '.', ',') }}
                                    {% else %}
                                        {{ (detailCommande.produit.prix * detailCommande.quantite) | number_format(2, '.', ',') }}
                                    {% endif %}
                                    €
                                </div>
                            </div>
                            <div class="flex items-center text-black mb-5 underline underline-offset-4 policePizza">
                                <a href="{{ path('_suppressionDuPanier', {'id': detailCommande.id}) }}"
                                   class="text-xl mt-2 hover:text-red-500 text-blue-800 duration-200 font-semibold justify-end">
                                    Supprimer l'article
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}


                <div class="flex justify-center items-center w-full mt-6 mb-2 policePizza">
                    <div class="text-3xl text-white font-bold">
                        Prix total : {{ prixDuPanier | number_format(2, '.', ',') }} €
                    </div>
                    <div class="ml-12">
                        <button type="button"
                                class=" text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            <a href="{{ path('_payementPanier') }}"
                               class="mr-1 text-3xl  font-bold ">Commander</a>
                            <svg class="rtl:rotate-180 w-8 h-8 ms-2" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg"
                                 fill="none" viewBox="0 0 14 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="M1 5h12m0 0L9 1m4 4L9 9"/>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% if detailsCommandePanier is empty %}
        <h3><a href="{{ path('_accueil') }}"
               class="ml-7 flex item-center justify-center hover:text-blue-500 mt-20 text-4xl policePizza text-blue-600 underline underline-offset-8">Votre
                panier est vide, cliquer ici pour commander une pizza ! </a></h3>
    {% endif %}

{% endblock %}