src/Entity/Collaborateur.php
<?php

namespace App\Entity;

use App\Repository\CollaborateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: CollaborateurRepository::class)]
class Collaborateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?string $nom = null;
    #[ORM\Column]
    private ?string $prenom = null;
    #[ORM\OneToMany(mappedBy: 'collaborateur', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(nullable: true)]
    private ?int $panier = null;

    #[ORM\Column(length: 10)]
    private ?string $telephone = null;

    #[ORM\OneToMany(mappedBy: 'livreur', targetEntity: Commande::class)]
    private Collection $commandesLivreur;

    #[ORM\Column(length: 255)]
    private ?string $Sexe = null;

    #[ORM\Column(length: 25)]
    private ?string $latitude = null;

    #[ORM\Column(length: 25)]
    private ?string $longitude = null;

    #[ORM\OneToMany(mappedBy: 'userId', targetEntity: UserMessage::class, orphanRemoval: true)]
    private Collection $userMessages;



    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->commandesLivreur = new ArrayCollection();
        $this->userMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }
    public function getNom(): ?string    {
        return $this->nom;
    }

    /**     * @param string|null $nom     */
    public function setNom(?string $nom): void    {
        $this->nom = $nom;
    }

    /**     * @return string|null     */
    public function getPrenom(): ?string    {
        return $this->prenom;
    }

    /**     * @param string|null $prenom     */
    public function setPrenom(?string $prenom): void    {
        $this->prenom = $prenom;
    }
    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setCollaborateur($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getCollaborateur() === $this) {
                $commande->setCollaborateur(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPanier(): ?int
    {
        return $this->panier;
    }

    public function setPanier(?int $panier): static
    {
        $this->panier = $panier;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandesLivreur(): Collection
    {
        return $this->commandesLivreur;
    }

    public function addCommandesLivreur(Commande $commandesLivreur): static
    {
        if (!$this->commandesLivreur->contains($commandesLivreur)) {
            $this->commandesLivreur->add($commandesLivreur);
            $commandesLivreur->setLivreur($this);
        }

        return $this;
    }

    public function removeCommandesLivreur(Commande $commandesLivreur): static
    {
        if ($this->commandesLivreur->removeElement($commandesLivreur)) {
            // set the owning side to null (unless already changed)
            if ($commandesLivreur->getLivreur() === $this) {
                $commandesLivreur->setLivreur(null);
            }
        }

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): static
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return Collection<int, UserMessage>
     */
    public function getUserMessages(): Collection
    {
        return $this->userMessages;
    }

    public function addUserMessage(UserMessage $userMessage): static
    {
        if (!$this->userMessages->contains($userMessage)) {
            $this->userMessages->add($userMessage);
            $userMessage->setUserId($this);
        }

        return $this;
    }

    public function removeUserMessage(UserMessage $userMessage): static
    {
        if ($this->userMessages->removeElement($userMessage)) {
            // set the owning side to null (unless already changed)
            if ($userMessage->getUserId() === $this) {
                $userMessage->setUserId(null);
            }
        }

        return $this;
    }


}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Form\ModificationMotDePasseFormType;
use App\Form\ModificationProfilFormType;
use App\Form\ProfilFormType;
use App\Repository\CollaborateurRepository;
use App\Repository\CommandeRepository;
use App\Repository\EtatRepository;
use App\Repository\IngredientRepository;
use App\Repository\ProduitRepository;
use App\Repository\TailleProduitRepository;
use App\Repository\UserMessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends AbstractController
{
    #[Route('/profil/{id}', name: '_profil')]
    public function index($id, CollaborateurRepository $collaborateurRepository, UserMessageRepository $userMessageRepository, CommandeRepository $commandeRepository, TailleProduitRepository $tailleProduitRepository, ProduitRepository $produitRepository): Response
    {
        $messagesNonLu = $userMessageRepository->findBy(['checked' => 0]);
        $utilisateur = $this->getUser();
//////////////////////////////// TOOLTIP ///////////////////////////////////////////////////////////////////////////////////////////
        $result = $this->tooltip($commandeRepository, $tailleProduitRepository, $produitRepository);
        if($result){
            $detailsCommandePanier = $result['detailsCommandePanier'];
            $prixDuPanier = $result['prixDuPanier'];
        } else {
            $detailsCommandePanier = [];
            $prixDuPanier = 0;
        }
//////////////////////////////////////////////////////////////////////////////
        $user = $collaborateurRepository->findOneBy(array('id' => $id));
        $numero = $user->getTelephone();
        $numeroAvecEspaces = chunk_split($numero, 2, ' ');
        return $this->render('profil/index.html.twig', compact('user', 'detailsCommandePanier', 'prixDuPanier', 'numeroAvecEspaces', 'messagesNonLu'));
    }

    #[Route('/modificationProfil/{id}', name: '_modificationProfil')]
    public function modificationProfil($id, CommandeRepository $commandeRepository, UserMessageRepository $userMessageRepository, TailleProduitRepository $tailleProduitRepository, ProduitRepository $produitRepository, CollaborateurRepository $collaborateurRepository, Request $requete, EntityManagerInterface $entityManager): Response
    {
        $messagesNonLu = $userMessageRepository->findBy(['checked' => 0]);
        $user = $collaborateurRepository->findOneBy(array('id' => $id));
        $utilisateurConnecter = $this->getUser();
//////////////////////////////// TOOLTIP ///////////////////////////////////////////////////////////////////////////////////////////
        $result = $this->tooltip($commandeRepository, $tailleProduitRepository, $produitRepository);
        if($result){
            $detailsCommandePanier = $result['detailsCommandePanier'];
            $prixDuPanier = $result['prixDuPanier'];
        } else {
            $detailsCommandePanier = [];
            $prixDuPanier = 0;
        }
//////////////////////////////////////////////////////////////////////////////
        $profilForm = $this->createForm(ModificationProfilFormType::class, $user);
        $profilForm->handleRequest($requete);

        if ($profilForm->isSubmitted() && $profilForm->isValid()) {

            $entityManager->persist($user);
            $entityManager->flush();
            if ($utilisateurConnecter !== null) {
                // Vérifiez ensuite le rôle de l'utilisateur grâce à al fonction isGranted qui fonctionne pareil que pour les twig
                if ($this->isGranted('ROLE_GERANT')) {
                    return $this->redirectToRoute('_gestionDesRoles'); // Si c'est le gérant on le renvoie vers tout les profils utilisateur
                } else {
                    return $this->redirectToRoute('_profil', ['id' => $id]); // Si c'est un utilisateur on le renvoie vers son profil
                }
            }
        }

        return $this->render('profil/modificationProfil.html.twig', compact('user', 'profilForm', 'detailsCommandePanier', 'prixDuPanier', 'messagesNonLu'));
    }

    #[Route('/modificationMotDePasse/{id}', name: '_modificationMotDePasse')]
    public function modificationMotDePasse($id, UserPasswordHasherInterface $userPasswordHasher, UserMessageRepository $userMessageRepository, CollaborateurRepository $collaborateurRepository, UserPasswordHasherInterface $passwordHasher, CommandeRepository $commandeRepository, TailleProduitRepository $tailleProduitRepository, ProduitRepository $produitRepository, Request $requete, EntityManagerInterface $entityManager): Response
    {
        $messagesNonLu = $userMessageRepository->findBy(['checked' => 0]);
        $user = $collaborateurRepository->findOneBy(array('id' => $id));
        $utilisateurConnecter = $this->getUser();
//////////////////////////////// TOOLTIP ///////////////////////////////////////////////////////////////////////////////////////////
        $result = $this->tooltip($commandeRepository, $tailleProduitRepository, $produitRepository);
        if($result){
            $detailsCommandePanier = $result['detailsCommandePanier'];
            $prixDuPanier = $result['prixDuPanier'];
        } else {
            $detailsCommandePanier = [];
            $prixDuPanier = 0;
        }
//////////////////////////////////////////////////////////////////////////////

        $mdpForm = $this->createForm(ModificationMotDePasseFormType::class);
        $mdpForm->handleRequest($requete);

        if ($mdpForm->isSubmitted() && $mdpForm->isValid()) {
            $newPassword = $mdpForm->get('newPassword')->getData();
            $ancienPassword = $mdpForm->getData()['password'];
            if ($userPasswordHasher->isPasswordValid($user, $ancienPassword)) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $newPassword
                    )
                );
                $entityManager->persist($user);
                $entityManager->flush();
                $this->addFlash('success', 'Le mot de passe a bien été modifié.');
                return $this->redirectToRoute('_profil', ['id' => $id]);
            } else {
                $this->addFlash('warning', 'Le mot de passe renseigné est incorrect');
                $this->addFlash('error', 'Mot de passe incorrect');
            }
        }
        return $this->render('profil/modificationPassword.html.twig', compact('mdpForm', 'prixDuPanier', 'detailsCommandePanier', 'messagesNonLu'));
    }

    public function prixDuPanier($derniereCommande, $tailleProduitRepository, $produitRepository, $detailsCommandePanier)
    {
        $prixDuPanier = 0; // Instancie une variable de prix de panier à 0 qui sera envoyé au twig
        $tailleLarge = $tailleProduitRepository->findOneBy(array('id' => 2)); // récupère la taille large pour une condition (prix)
        if ($derniereCommande != null) { // Si il y a une dernière commande
            $etatDerniereCommande = $derniereCommande->getEtat();
            if ($etatDerniereCommande->getId() == 1) { // Si elle est a l'état créé
                foreach ($detailsCommandePanier as $detail) {
                    $idProduit = $detail->getProduit()->getId();
                    $pizza = $produitRepository->findOneBy(array('id' => $idProduit));
                    if ($detail->getTaille() === $tailleLarge) { // Si il y a une taille large on change le prix
                        $prixDuDetail = 5 + ($pizza->getPrix() * $detail->getQuantite());
                    } else {
                        $prixDuDetail = ($pizza->getPrix() * $detail->getQuantite());
                    }

                    $prixDuPanier = ($prixDuPanier + $prixDuDetail); // Total du panier
                }
            }
        }
        return $prixDuPanier;
    }

    #[Route('/profilsClient', name: '_profilsClient')]
    public function profilsClient(Request $request, IngredientRepository $ingredientRepository, EtatRepository $etatRepository, CommandeRepository $commandeRepository, EntityManagerInterface $entityManager)
    {
        $etatLivraison = $etatRepository->findOneBy(array('id' => 4)); // État livré
        $commandesALivrer = $commandeRepository->findBy(['etat' => $etatLivraison,]); // Récupération des commandes prêtes à être livrées
        $adresseLivraison = [];

        foreach ($commandesALivrer as $index => $commande) {
            $adresse = $commande->getCollaborateur()->getAdresse(); // Récupération de l'adresse de la commande
            $adresseLivraison[$index] = $adresse; // Tableau associatif

        }
        return new JsonResponse(['adresses' => $adresseLivraison]);
    }

    #[Route('/coordonneesClient', name: '_coordonneesClient')]
    public function coordonneesClient(Request $request, IngredientRepository $ingredientRepository, EtatRepository $etatRepository, CommandeRepository $commandeRepository, EntityManagerInterface $entityManager)
    {
        $etatLivraison = $etatRepository->findOneBy(array('id' => 4)); // État livré
        $commandesALivrer = $commandeRepository->findBy(['etat' => $etatLivraison,]); // Récupération des commandes prêtes à être livrées
        $adresseLivraison = [];

        foreach ($commandesALivrer as $index => $commande) {
            $latitude = $commande->getCollaborateur()->getLatitude();
            $longitude = $commande->getCollaborateur()->getLongitude(); // Récupération de l'adresse de la commande
            $adresseLivraison[$index] = [$latitude, $longitude]; // Tableau associatif
        }
        return new JsonResponse(['adresses' => $adresseLivraison]);
    }

templates/profil/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}PizzaOnLine - Profil{% endblock %}

{% block body %}
    <h1 class="flex content-center justify-center text-4xl mt-4 mb-6 text-gray-50 underline underline-offset-8"> Profil de {{ user.prenom }} {{ user.nom }}</h1>
    <div class="flex flex-wrap justify-center mb-12 mt-8">

    <div class="w-1/3">
        <div class="flex justify-center items-center">
            {% for message in app.flashes('success') %}
                <div class=" alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-first-name">
                    Nom :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ user.nom }}
                </div>
            </div>
            <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-last-name">
                    Prenom :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ user.prenom }}
                </div>
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-password">
                    Sexe :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ user.sexe }}
                </div>
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-password">
                    Email :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ user.email }}
                </div>
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-password">
                    Téléphone :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ numeroAvecEspaces }}
                </div>

            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                       for="grid-password">
                    Adresse :
                </label>
                <div class="form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white">
                    {{ user.adresse }}
                </div>
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-4">
            <div class="w-full px-3">
                <a href="{{ path ('_modificationMotDePasse', { 'id': user.id }) }}"
                   class=" text-2xl text-blue-500 underline underline-offset-4"> Modifier le mot de passe</a>
            </div>
        </div>
        {% if is_granted('ROLE_GERANT') %}
        <div class="flex flex-wrap -mx-3 mb-2">
            {% else %}
            <div class="flex flex-wrap -mx-3 mb-2 hidden">
                {% endif %}
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-50 text-lg font-bold mb-2"
                           for="grid-password">
                        Rôles :
                    </label>
                    <div class="text-gray-700 flex flex-col">
                        {% for role in user.roles %}
                            <div class="text-gray-50 text-lg">
                                {{ role }}
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
            <div class="flex justify-center items-center mb-12">
                <button type="submit"
                        class="btn flex justify-center items-center text-3xl text-white bg-blue-500 hover:bg-blue-700 font-bold">
                    <a href="{{ path ('_modificationProfil', { 'id': user.id }) }}"
                       class=" text-2xl underline underline-offset-4"> Modifier ses informations</a>
                </button>
            </div>
        </div>
    </div>


{% endblock %}

templates/profil/modificationPassword.html.twig
{% extends 'base.html.twig' %}
{% block title %}PizzaOnLine - Modification mot de passe{% endblock %}

{% block body %}
    <h2 class="flex item-center justify-center text-5xl mt-2 mb-16 font-semibold text-gray-50"> Modification du mot de
        passe</h2>

    <div class="flex justify-center items-center">
        {% for message in app.flashes('warning') %}
            <div class="alert alert-error w-2/5">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    <div class="w-full flex justify-center">

        <div class="w-1/2 flex justify-center items-center flex-col bg-gray-500 border border-2 border-gray-100">
            {{ form_start(mdpForm, {'attr': {'class': 'w-full'}}) }}
            <div class="w-full flex mt-6">
                <div class="w-1/2 flex justify-end text-3xl text-gray-50 mr-5 mb-6 ">
                    {{ form_label(mdpForm.password.first) }}&nbsp;:
                </div>
                <div class="w-1/2 text-3xl ml-5 mb-6 text-black font-semibold">
                    {{ form_widget(mdpForm.password.first, {'attr': {'class': 'w-3/4'}}) }}
                </div>
            </div>

            <div class="w-full flex">
                {{ form_errors(mdpForm.password) }}
            </div>
            <div class="w-full flex">
                <div class="w-1/2 flex justify-end text-3xl mr-5 mb-6 text-gray-50"> {{ form_label(mdpForm.password.second) }}&nbsp;:
                </div>
                <div class="w-1/2 text-3xl ml-5 mb-6 text-black font-semibold"> {{ form_widget(mdpForm.password.second, {'attr': {'class': 'w-3/4'}}) }}</div>
            </div>
            <div class="w-full flex">
                <div class="w-1/2 flex justify-end text-3xl mr-5 mb-6 text-gray-50"> {{ form_label(mdpForm.newPassword) }}&nbsp;:
                </div>
                <div class="w-1/2 text-3xl ml-5 mb-6 text-black font-semibold"> {{ form_widget(mdpForm.newPassword, {'attr': {'class': 'w-3/4'}}) }}</div>
            </div>

            <div class="flex justify-center item-center text-4xl hover:text-red-500 duration-200 font-bold mt-6 mb-4">
                {{ form_widget(mdpForm.ajouter, {'attr': {'class': 'btn w-3/5 flex justify-center items-center text-3xl text-white bg-blue-600 hover:bg-blue-700 font-bold'}}) }}
            </div>
            {{ form_end(mdpForm) }}
        </div>


    </div>
{% endblock %}